image: "python:latest"

stages:
    - build
    - deploy

build_exe:
    stage: build
    script:
        - Invoke-WebRequest -Uri https://www.python.org/ftp/python/3.10.9/python-3.10.9-amd64.exe -OutFile python-installer.exe
        - .\python-installer.exe /quiet InstallAllUsers=1 PrependPath=1 Include_test=0 | Out-Null
        - Invoke-WebRequest -Uri https://prdownloads.sourceforge.net/nsis/nsis-3.08-setup.exe?download -OutFile nsis-installer.exe -UserAgent [Microsoft.PowerShell.Commands.PSUserAgent]::FireFox
        - .\nsis-installer.exe /S /D=C:\NSIS
        - $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
        - pip install -r requirements.txt
        - pip install cx-Freeze
        - python build_exe.py build --build-exe  WindowsBuild\Portable
        - C:\NSIS\Bin\makensis.exe .\deploy\Installer.nsi
        - cp .\deploy\*.exe .\WindowsBuild\

    artifacts:
        paths:
            - WindowsBuild
        expire_in: 1 month
    only:
        - tags
    tags:
        - windows

pip_deploy:
    stage: deploy
    script:
        - pip install twine build
        - python -m build --sdist --wheel
        - twine upload -u "$PYPI_USERNAME" -p "$PYPI_PASSWORD" dist/*
    only:
        - tags

sourceforge_deploy:
    stage: deploy
    script:
        - pip install pysftp requests
        - python deploy/sourceforge.py
    only:
        - tags
