#epends_on:
#    - check-starting

steps:
    pypi_deploy:
        image: python:3.13
        commands:
            - pip install twine build
            - python -m build
            - twine upload -u "$PYPI_USERNAME" -p "$PYPI_PASSWORD" dist/*
        environment:
            PYPI_USERNAME:
                from_secret: PYPI_USERNAME
            PYPI_PASSWORD:
                from_secret: PYPI_PASSWORD

when:
    event: tag
